---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Maaz Saeed"
date: "2023-09-22"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
# install the package 'Lahman'
#install.packages('Lahman')
# load the package
library(Lahman)
library(dplyr)
library(magrittr)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has 3,015 observations and 48 variables.

### Exercise 2
```{r Mets 2004-2012}
mets <- Teams  %>% 
  dplyr::filter(teamID == "NYN")
my_mets <- mets %>% 
  dplyr::filter(yearID > 2003 & yearID < 2013)
my_mets %>% 
  dplyr::select(teamID, yearID, W, L)
```
The win loss records for the New York Mets, for the years 2004 - 2012 are displayed above.

### Exercise 3
```{r gathering runs scored and allowed}
mets_ben <- Teams |>
  dplyr::select(teamID, yearID, R, RA,) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben

mets_ben <- mets_ben |>
  dplyr::rename(RS = R)    # new name = old name
mets_ben
```


...

### Exercise 4
```{r}

```

...

### Exercise 5

...

### Exercise 6

...

### Exercise 7

...

### Exercise 8

...

### Exercise 9

...

### Exercise 10

...
